// Regenerates src/wasm-module.ts from wasm/hayahash.wasm. Run via
// wasm/build.sh (which also rebuilds the wasm) or `npm run build:embed`.
import { mkdir, readFile, writeFile } from "node:fs/promises";

const wasm = await readFile(new URL("../wasm/hayahash.wasm", import.meta.url));
const b64 = wasm.toString("base64");

// Keep lines short so the generated file stays diffable.
const chunks = [];
for (let i = 0; i < b64.length; i += 72) {
	chunks.push(`\t"${b64.slice(i, i + 72)}"`);
}

const out = `// Generated by scripts/embed.mjs from wasm/hayahash.wasm - do not edit.
// The wasm module is the reference hayahash.h compiled for
// wasm32-freestanding; see wasm/build.sh for the exact command.
// ${wasm.length} bytes, small enough for synchronous instantiation
// everywhere (browsers only restrict sync compilation above 4 KB).
export const wasmBase64: string = [
${chunks.join(",\n")},
].join("");
`;

await mkdir(new URL("../src", import.meta.url), { recursive: true });
await writeFile(new URL("../src/wasm-module.ts", import.meta.url), out);
console.log(`embedded ${wasm.length} bytes into src/wasm-module.ts`);
