#!/bin/sh
# Assemble the generated artifacts for website/playground.html.
#
# The playground needs three build products that stay out of git on
# purpose:
#
#   website/vendor/*.js   the npm package modules (js/dist), so the
#                         page hashes with the exact code the package
#                         ships
#   website/bench.wasm    the tests/wasm shootout module, stripped;
#                         it embeds rapidhash (MIT) and xxHash (BSD-2), so
#                         the binary is built at deploy time and
#                         never committed
#   website/vendor/kat.txt  known answers of that exact module; the
#                         page verifies all of them before it
#                         measures
#
# The Pages workflow (.github/workflows/static.yml) runs this script
# before upload. Run it locally to preview the playground:
#
#   scripts/build-playground.sh
#   python3 -m http.server -d website 8000
#
# Requires zig (any version that targets wasm32), node, and npm.
set -eu
cd "$(dirname "$0")/.."

# 1. The npm package modules. dist/ is generated by tsc and not
#    committed, so build it here.
(cd js && npm ci --ignore-scripts && npm run build)
mkdir -p website/vendor
cp js/dist/index.js js/dist/pure.js js/dist/wasm.js js/dist/wasm-module.js \
	website/vendor/

# 2. The shootout module. Force a rebuild so a stale unstripped
#    bench.wasm from a test run cannot leak in. --strip-all drops the
#    name section (952 KB -> 14 KB) and changes no code.
rm -f tests/wasm/bench.wasm
make -C tests/wasm bench.wasm CFLAGS="-O3 -Wl,--strip-all"
cp tests/wasm/bench.wasm website/bench.wasm

# 3. Known answers of the module we just built. The hayahash subset
#    must match the committed, natively verified kat_haya.txt. This
#    fails the deploy if hayahash.h drifts from the pinned truth.
node tests/wasm/driver.mjs tests/wasm/bench.wasm --kat > website/vendor/kat.txt
grep '^haya' website/vendor/kat.txt | diff - tests/wasm/kat_haya.txt

printf 'playground artifacts ready: website/bench.wasm (%s bytes), website/vendor/\n' \
	"$(wc -c < website/bench.wasm | tr -d ' ')"
