#!/bin/sh
# Assemble the generated artifacts for website/playground.html.
#
# The playground needs a content-versioned asset bundle that stays out of
# git on purpose:
#
#   website/assets/<hash>/playground.js
#   website/assets/<hash>/vendor/*.js
#   website/assets/<hash>/bench.wasm
#   website/assets/<hash>/vendor/kat.txt
#
# playground-assets.json is the only mutable pointer. The HTML revalidates it
# and imports the versioned entry module; every relative import and fetch then
# stays inside the same immutable directory. The unversioned bench.wasm and
# vendor/ copies remain as compatibility aliases for browsers that cached the
# pre-versioning HTML shell.
#
# The Pages workflow (.github/workflows/static.yml) runs this script
# before upload. Run it locally to preview the playground:
#
#   scripts/build-playground.sh
#   python3 -m http.server -d website 8000
#
# Requires zig (any version that targets wasm32), node, and npm.
set -eu
cd "$(dirname "$0")/.."

# 1. The npm package modules. dist/ is generated by tsc and not
#    committed, so build it here.
(cd js && npm ci --ignore-scripts && npm run build)
mkdir -p website/vendor
cp js/dist/index.js js/dist/pure.js js/dist/wasm.js js/dist/wasm-module.js \
	website/vendor/

# 2. The shootout module. Force a rebuild so a stale unstripped
#    bench.wasm from a test run cannot leak in. --strip-all drops the
#    name section (952 KB -> 14 KB) and changes no code.
rm -f tests/wasm/bench.wasm
make -C tests/wasm bench.wasm CFLAGS="-O3 -Wl,--strip-all"
cp tests/wasm/bench.wasm website/bench.wasm

# 3. Known answers of the module we just built. The hayahash subset
#    must match the committed, natively verified kat_haya.txt. This
#    fails the deploy if hayahash.h drifts from the pinned truth.
node tests/wasm/driver.mjs tests/wasm/bench.wasm --kat > website/vendor/kat.txt
grep '^haya' website/vendor/kat.txt | diff - tests/wasm/kat_haya.txt

# 4. Copy the complete, mutually compatible set into a temporary namespace,
#    hash file names and contents, then publish it under that hash. The helper
#    writes playground-assets.json only after the versioned directory exists.
rm -rf website/assets
mkdir -p website/assets/.staging/vendor
cp website/playground.js website/bench.wasm website/assets/.staging/
cp website/vendor/index.js website/vendor/pure.js website/vendor/wasm.js \
	website/vendor/wasm-module.js website/vendor/kat.txt \
	website/assets/.staging/vendor/

asset_version="$(
	node scripts/version-playground.mjs \
		website/assets/.staging website/playground-assets.json
)"

printf 'playground artifacts ready: assets/%s/ (%s-byte wasm)\n' \
	"$asset_version" "$(wc -c < website/bench.wasm | tr -d ' ')"
